import {
  regDate, regHouseNumber, regLettersNumbersOnly,
  regName, regNumbersAndSpace, regNumbersMore,
  regNumbersOnly, regPatronymic, regStreet, regSurname, regTextNumberMore,
} from '@/store/regularExp';
import actions from './actions';
import getters from './getters';
import mutations from './mutations';

export default {
  namespaced: true,
  state: {
    allTariffs: [
      {
        title: 'Старт',
        htmlId: 'start',
        description: '0 ₽ в месяц \n 3% от суммы вывода',
        firstList: 'Обслуживание бесплатно, если тратить все деньги на АЗС',
        secondList: 'Подходит для новых пользователей ТаксиПро',
        thirdList: 'Моментальные выплаты',
        isChecked: true,
      },
      {
        title: 'Комфорт',
        htmlId: 'comfort',
        description: '690 ₽ в месяц \n +1% от суммы вывода',
        firstList: 'Низкая абонентская плата',
        secondList: 'Удобные автоматические еженедельные платежи',
        thirdList: 'Скидка на комиссию банка',
        isChecked: false,
      },
      {
        title: 'Премиум',
        htmlId: 'premium',
        description: '990 ₽ в месяц \n +1% от суммы вывода',
        firstList: 'Безлимитные моментальные платежи в любое время',
        secondList: 'Оптимальный тариф для активных водителей',
        thirdList: 'С наличных заказов не берем комиссию',
        isChecked: false,
      },
    ],
    allAgregators: {
      gett: {
        id: 0,
        title: 'gett',
        htmlId: 'gett',
        img: '/assets/images/step2/0.jpeg',
        isChecked: false,
      },
      yandexTaxi: {
        id: 1,
        title: 'yandexTaxi',
        htmlId: 'yandexTaxi',
        img: '/assets/images/step2/1.jpeg',
        isChecked: false,
      },
      citymobile: {
        id: 2,
        title: 'citymobile',
        htmlId: 'citymobile',
        img: '/assets/images/step2/2.jpeg',
        isChecked: false,
      },
      uber: {
        id: 3,
        title: 'uber',
        htmlId: 'uber',
        img: '/assets/images/step2/3.jpeg',
        isChecked: false,
      },
      didi: {
        id: 4,
        title: 'didi',
        htmlId: 'didi',
        img: '/assets/images/step2/4.jpeg',
        isChecked: false,
      },
    },
    registrationData: {
      tariffName: {
        type: 'tariff',
        text: 'Тариф',
        value: '',
      },
      agregators: {
        type: 'agregators',
        text: 'Агрегаторы',
        value: [],
      },
      passport: {
        type: 'passport',
        text: 'Паспортные данные',
        value: [
          {
            id: 'surname',
            placeholder: 'Иванов',
            text: 'Фамилия',
            value: '',
            errorMessage: '',
            validate: {
              regName: regSurname,
              min: 1,
              max: 32,
            },
            isCorrect: false,
            directive: '',
          },
          {
            id: 'name',
            placeholder: 'Петр',
            text: 'Имя',
            value: '',
            errorMessage: '',
            validate: {
              regName,
              min: 1,
              max: 32,
            },
            isCorrect: false,
            directive: '',
          },
          {
            id: 'patronymic',
            placeholder: 'Петрович',
            text: 'Отчество (если есть)',
            value: '',
            errorMessage: '',
            validate: {
              regName: regPatronymic,
              min: 0,
              max: 32,
            },
            isCorrect: true,
            directive: '',
          },
          {
            id: 'birthday',
            placeholder: '27/08/1980',
            text: 'Дата рождения',
            value: '',
            errorMessage: '',
            validate: {
              regName: regDate,
              min: 9,
              max: 11,
            },
            isCorrect: false,
            directive: 'v-date',
          },
          {
            id: 'passportNumber',
            placeholder: '8807 198022',
            text: 'Серия и номер паспорта',
            value: '',
            errorMessage: '',
            validate: {
              regName: regNumbersAndSpace,
              min: 10,
              max: 15,
            },
            isCorrect: false,
            directive: 'v-passport-numbers',
          },
          {
            id: 'passportWhoGive',
            placeholder: 'ТП №1 в гор. округе Тольятти...',
            text: 'Кем выдан',
            value: '',
            errorMessage: '',
            validate: {
              regName: regTextNumberMore,
              min: 10,
              max: 64,
            },
            isCorrect: false,
            directive: '',
          },
          {
            id: 'passportWhenGive',
            placeholder: '27/08/2019',
            text: 'Дата выдачи',
            value: '',
            errorMessage: '',
            validate: {
              regName: regDate,
              min: 9,
              max: 11,
            },
            isCorrect: false,
            directive: 'v-date',
          },
          {
            heading: 'Адрес регистрации',
            id: 'city',
            placeholder: 'Тольятти',
            text: 'Город',
            value: '',
            errorMessage: '',
            validate: {
              regName,
              min: 1,
              max: 32,
            },
            isCorrect: false,
            directive: '',
          },
          {
            id: 'region',
            placeholder: 'Московская',
            text: 'Регион/Область (если есть)',
            value: '',
            errorMessage: '',
            validate: {
              regName: regPatronymic,
              min: 0,
              max: 32,
            },
            isCorrect: true,
            directive: '',
          },
          {
            id: 'street',
            placeholder: 'Индустриальная',
            text: 'Улица',
            value: '',
            errorMessage: '',
            validate: {
              regName: regStreet,
              min: 1,
              max: 64,
            },
            isCorrect: false,
            directive: '',
          },
          {
            id: 'house',
            placeholder: '50',
            text: 'Дом',
            value: '',
            errorMessage: '',
            validate: {
              regName: regHouseNumber,
              min: 0,
              max: 10,
            },
            isCorrect: false,
            directive: '',
            class: 'inputHouse',
          },
          {
            id: 'flat',
            placeholder: '44',
            text: 'Квартира',
            value: '',
            errorMessage: '',
            validate: {
              regName: regNumbersOnly,
              min: 0,
              max: 10,
            },
            isCorrect: true,
            directive: '',
            class: 'inputFlat',
          },
        ],
      },
      driverLessons: {
        type: 'driverLessons',
        text: 'Данные В.У.',
        value: [
          {
            id: 'driverNumbers',
            placeholder: '2233 444555',
            text: 'Сериия и номер В.У.',
            value: '',
            errorMessage: '',
            validate: {
              regName: regNumbersAndSpace,
              min: 10,
              max: 15,
            },
            isCorrect: false,
            directive: 'v-passport-numbers',
          },
          {
            id: 'whenDriverLessonsGive',
            placeholder: '01/01/2020',
            text: 'Дата выдачи',
            value: '',
            errorMessage: '',
            validate: {
              regName: regDate,
              min: 9,
              max: 11,
            },
            isCorrect: false,
            directive: 'v-date',
          },
          {
            id: 'whenDriverLessonsClose',
            placeholder: '01/01/2000',
            text: 'Срок выдачи',
            value: '',
            errorMessage: '',
            validate: {
              regName: regDate,
              min: 9,
              max: 11,
            },
            isCorrect: false,
            directive: 'v-date',
          },
        ],
      },
      car: {
        type: 'car',
        text: 'Данные Т.C.',
        value: [
          {
            id: 'brand',
            placeholder: 'KIA',
            text: 'Марка автомобиля',
            value: '',
            errorMessage: '',
            validate: {
              regName,
              min: 1,
              max: 128,
            },
            isCorrect: false,
            directive: '',
          },
          {
            id: 'model',
            placeholder: 'RIO',
            text: 'Модель автомобиля',
            value: '',
            errorMessage: '',
            validate: {
              regName,
              min: 1,
              max: 128,
            },
            isCorrect: false,
            directive: '',
          },
          {
            id: 'year',
            placeholder: '2019',
            text: 'Год автомобиля',
            value: '',
            errorMessage: '',
            validate: {
              regName: regNumbersOnly,
              min: 3,
              max: 5,
            },
            isCorrect: false,
            directive: '',
          },
          {
            id: 'color',
            placeholder: 'черный',
            text: 'Цвет автомобиля',
            value: '',
            errorMessage: '',
            validate: {
              regName: regTextNumberMore,
              min: 1,
              max: 99,
            },
            isCorrect: false,
            directive: '',
          },
          {
            id: 'carNumber',
            placeholder: 'е756уе150',
            text: 'Регистрационный знак ТС',
            value: '',
            errorMessage: '',
            validate: {
              regName: regTextNumberMore,
              min: 6,
              max: 10,
            },
            isCorrect: false,
            directive: '',
          },
          {
            id: 'VIN',
            placeholder: 'vyfu65566fufi76uff6u',
            text: 'VIN',
            value: '',
            errorMessage: '',
            validate: {
              regName: regLettersNumbersOnly,
              min: 7,
              max: 99,
            },
            isCorrect: false,
            directive: '',
          },
          {
            id: 'numberСertificate',
            placeholder: '54 67 № 890909',
            text: 'Номер свидетельства ТС',
            value: '',
            errorMessage: '',
            validate: {
              regName: regNumbersMore,
              min: 7,
              max: 99,
            },
            isCorrect: false,
            directive: 'v-passport-numbers',
          },
        ],
      },
      license: {
        heading: 'Данные лицензии',
        id: 'license',
        placeholder: '0765643',
        type: 'license',
        text: 'Номер лицензии',
        errorMessage: '',
        validate: {
          regName: regNumbersOnly,
          min: 5,
          max: 20,
        },
        isCorrect: false,
        directive: '',
        value: '',
      },
    },
  },
  mutations,
  actions,
  getters,
};
